##spring:
##  datasource:
##    url: jdbc:mysql://localhost:3306/cloud_vendor?useSSL=false
##    username: root
##    password: Taisin@123
##
##    #JPA Settings
##    #jpa.hibernate.ddl_auto-: create    #or update
##    spring:jpa:hibernate:ddl-auto=update:

